### ISSUE TITLE
Feedback HW2 task 2

### ISSUE THREAD

**Issue by LVALL** [Eiserich/RubyHW#3]
Ви взяли за зразок код з [першого посилання](https://medium.com/the-cabin-coder/making-my-own-tamagotchi-game-on-ruby-131ce4e60c93), що гуглиться для тамагочі на рубі, який надалі збив ваше уявлення того, як все повинно працювати з ООП підходом.

Немає взаємодії з об'єктом, усі методи є методами класу і все працює на рівні класу. 

Спробуйте розібрати приклад за посиланням, наведеним в формі та знайти різницю між принципом реалізації, наведеним там, та вашою реалізацією, побачити різницю між методами класу та методами екземпляру.

[class Dragon ...](https://gist.github.com/Kashoid23/c724dc3d972a83bb293bd84bd82d61de#:~:text=%D0%9B%D0%B0%D0%B4%D0%BD%D0%BE%2C%20%D0%B4%D0%B0%D0%B2%D0%B0%D0%B9%D1%82%D0%B5%20%D0%BF%D0%BE%D0%BF%D1%80%D0%BE%D0%B1%D1%83%D0%B5%D0%BC%3A-,class%20Dragon,-def%20initialize%20name)

**Comment by Eiserich** [comment]
я спробував переробити тамагочі.
