### ISSUE TITLE
Отзыв на работу HW4

### ISSUE THREAD

**Issue by fillson22** [Eiserich/RubyHW#4]
Всё работает. Ты постарался.
Но)))
1. Нет возможности закончить игру в любой момент.

2. Иногда, так как у тебя рандом, life приобретает значение "-1", хотя ты прописываешь на странице, что игра закончиться при значении "0"

3. Идёт дубляж:
def sleep
      @hunger -= rand(10) <---------------
      @energy += rand(20)
      time_pass <---------- здесь также есть @hunger -=...
    end

  private

  def time_pass
    @hygiene -= rand(10)
    @fun     -= rand(10)
    @hunger  -= rand(10) <----------------
    @energy  -= rand(10)
    @health  -= rand(10)

4. Код написан в принципе аккуратно но есть замечание к "end" не всегда в нужном столбе
      
    when "/vet"
      return response_redirect("/") if pet.nil?
      if pet.alive
        pet.vet
      Rack::Response.new(render("index.html.erb")) **<--------- можно создать метод, действие повторяющееся, но и так можно))**
        else
        response_redirect("/game_over")
        end<--------------- и это повторяющаяся ошибка

5. На счет оформления. Задачи сделать очень красиво не было, но аккуратно, в рядочек, рядом можно было бы.
Будет время сделаешь, хотя на вкус и цвет товарища нет.

В целом приятно было поработать.

**Comment by Eiserich** [comment]
Спасибо, я попробовал исправить  эти замечания.
