### ISSUE TITLE
Feedback to HW 3

### ISSUE THREAD

**Issue by MaksHostroushko** [Eiserich/RubyHW#5]
Looks great!
Let's add some improvements

1. https://github.com/Eiserich/RubyHW/blob/main/HW3/pet_with_html/pet_with_html.rb#L1..L2
Please, add an empty line between `require` and `class`

2.https://github.com/Eiserich/RubyHW/blob/main/HW3/pet_with_html/pet_with_html.rb#L24..L29
I believe, in this case, we can avoid code duplicating
For example,
`@health = @hunger = @hygiene =  @fun = @energy = rand(50..89) `
Please, do the same for `else` block

**Comment by Eiserich** [comment]
done
