### ISSUE TITLE
Feedback Articles controller

### ISSUE THREAD

**Issue by RoRElessar** [Eiserich/RubyHW#9]
- [x] Why `show`, `destroy` and `update` actions are private methods? I should be able to get a specific article, update it, and destroy it.
- [x] Don't use `!` in the methods like `create`, `update` or `destroy`
- [x] Pay attention to code style, especially to idents. Use 2 spaces to ident nesting.

You should use `rubocop` to avoid basic codestyle errors.

**Comment by Eiserich** [comment]
done
